version: '3.2'
services:
 autoupdater:
  container_name: autoupdater
  build:
   context: ./elrond-updater/
   dockerfile: Dockerfile
  environment:
   - GITHUBTOKEN=${GITHUB_TOKEN}
  restart: always
  volumes:
   - /var/run/docker.sock:/var/run/docker.sock
   - "./volumes/:/volumes"