version: '3.2'
services:
 elrond-1:
  image: elrond:0.1
  container_name: elrond-1
  restart: unless-stopped
  ports:
   - 8081:8080
  volumes:
          - "./volumes/node-1/:/home/elrond/elrond-nodes/node-0/"
