version: '3.2'
services:
 autoupdater:
  container_name: autoupdater
  build:
   context: ./elrond-updater/
   dockerfile: Dockerfile
  environment:
   - GITHUBTOKEN: $GITHUBTOKEN
  restart: always
  volumes:
   - /var/run/docker.sock:/var/run/docker.sock
   - "./volumes/:/volumes"
 <node-name>:
  image: elrond:botn
  container_name: nodename
  restart: unless-stopped
  environment:
   - NODE_NAME=<node-name>
   - GITHUBTOKEN: $GITHUBTOKEN
  ports:
   - <api_port>:8080
  volumes:
   - "./volumes/<node-name>/:/home/elrond/elrond-nodes/node-0/"
