version: '3.2'
services:
 autoupdater:
  container_name: autoupdater
  build:
   context: ./elrond-updater/
   dockerfile: Dockerfile
  restart: always
  volumes:
   - /var/run/docker.sock:/var/run/docker.sock
   - "./volumes/:/volumes"
 <node-name>:
  image: <node-name>:botn
  container_name: nodename
  restart: unless-stopped
  ports:
   - <api_port>:8080
  volumes:
          - "./volumes/<node-name>/:/home/elrond/elrond-nodes/node-0/"
