version: '3.2'
services:
 autoupdater:
  container_name: autoupdater
  build:
   context: ./elrond-updater/
   dockerfile: Dockerfile
  restart: always
  volumes:
   - /var/run/docker.sock:/var/run/docker.sock
   - "./volumes/:/volumes"
 elrond-1:
  image: elrond:0.1
  container_name: nodename
  restart: unless-stopped
  ports:
   - 8081:8080
  volumes:
          - "./volumes/nodename/:/home/elrond/elrond-nodes/node-0/"
